-- AlterTable
ALTER TABLE "ArtistSpecialty" ADD COLUMN "priceToman" BIGINT,
ADD COLUMN "durationMin" INTEGER,
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "note" TEXT,
ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SalonService" ADD COLUMN "priceToman" BIGINT,
ADD COLUMN "durationMin" INTEGER,
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
